CREATE OR REPLACE FUNCTION REMOVE_DEAD_LINKS()
    RETURNS TRIGGER
    LANGUAGE plpgsql AS
$$
BEGIN
    WITH VALID_COORDINATES_IDS AS
             (SELECT ORGANIZATIONS.COORDINATES_ID
              FROM ORGANIZATIONS)
    DELETE
    FROM COORDINATES
    WHERE NOT (COORDINATES.ID = ANY (SELECT * FROM VALID_COORDINATES_IDS));

    WITH VALID_ADDRESSES_IDS AS
             (SELECT ORGANIZATIONS.POSTAL_ADDRESS_ID
              FROM ORGANIZATIONS)
    DELETE
    FROM ADDRESS
    WHERE NOT (ADDRESS.ID = ANY (SELECT * FROM VALID_ADDRESSES_IDS));

    WITH VALID_LOCATIONS_IDS AS
             (SELECT ADDRESS.LOCATION_ID
              FROM ADDRESS)
    DELETE
    FROM LOCATION
    WHERE NOT (LOCATION.ID = ANY (SELECT * FROM VALID_LOCATIONS_IDS));

    RETURN NULL;
END;
$$;

CREATE OR REPLACE TRIGGER DEAD_LINKS_REMOVER
    AFTER UPDATE OR INSERT OR DELETE
    ON ORGANIZATIONS
    FOR STATEMENT
EXECUTE FUNCTION REMOVE_DEAD_LINKS();
